try:
    print(x)
except:
    print("An Exception Occured")